"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language="en"|"sq";
const LANGUAGE_STORE="hiddentify_language";

const sq:Record<string,string>={
  "Language":"Gjuha",
  "English":"Anglisht",
  "Albanian":"Shqip",
  "How to play":"Si të luani",
  "Join a case":"Hyr në një çështje",
  "New case":"Çështje e re",
  "Leave room":"Dil nga dhoma",
  "Reconnecting to your case…":"Duke u rilidhur me çështjen…",
  "CASE FILE · UNSOLVED":"DOSJE ÇËSHTJEJE · E PAZGJIDHUR",
  "Somebody in your group is":"Dikush në grupin tuaj po",
  "lying.":"gënjen.",
  "A fresh murder case for 3–10 friends. Every phone receives a character, secrets, and only part of the truth.":"Një çështje e re vrasjeje për 3–10 miq. Çdo telefon merr një personazh, sekrete dhe vetëm një pjesë të së vërtetës.",
  "Start a new case":"Fillo një çështje të re",
  "No download":"Pa shkarkim",
  "Private roles":"Role private",
  "Two game modes":"Dy mënyra loje",
  "Enter the investigation":"Hyr në hetim",
  "Choose how you enter":"Zgjidh si do të hysh",
  "Account or guest":"Llogari ose vizitor",
  "Play with an account":"Luaj me llogari",
  "Save your username and stay signed in on this device.":"Ruaj username-in dhe qëndro i kyçur në këtë pajisje.",
  "Continue as":"Vazhdo si",
  "Continue as guest":"Vazhdo si vizitor",
  "Use a temporary name and enter immediately—no registration.":"Përdor një emër të përkohshëm dhe hyr menjëherë—pa regjistrim.",
  "ACCOUNT":"LLOGARI",
  "GUEST":"VIZITOR",
  "Account access":"Hyrje në llogari",
  "Sign in or create account":"Hyr ose krijo llogari",
  "Use your own email. No ChatGPT account is required.":"Përdor email-in tënd. Nuk kërkohet llogari ChatGPT.",
  "Continue through secure sign-in. Hiddentify never receives your password.":"Vazhdo përmes hyrjes së sigurt. Hiddentify nuk e merr kurrë fjalëkalimin tënd.",
  "Continue to secure sign-in":"Vazhdo te hyrja e sigurt",
  "Signed in as":"I kyçur si",
  "Choose your username":"Zgjidh username-in",
  "This is the name friends will see in every room.":"Ky është emri që miqtë do të shohin në çdo dhomë.",
  "Saving username…":"Duke ruajtur username-in…",
  "Save username":"Ruaj username-in",
  "Welcome back":"Mirë se u ktheve",
  "Create your account":"Krijo llogarinë",
  "Log in":"Hyr",
  "Sign up":"Regjistrohu",
  "Username":"Username",
  "Email":"Email",
  "Password":"Fjalëkalimi",
  "Confirm password":"Konfirmo fjalëkalimin",
  "At least 8 characters":"Të paktën 8 karaktere",
  "Passwords do not match.":"Fjalëkalimet nuk përputhen.",
  "Use at least 8 characters for your password.":"Përdor të paktën 8 karaktere për fjalëkalimin.",
  "Creating account…":"Duke krijuar llogarinë…",
  "Signing in…":"Duke hyrë…",
  "Check your email to confirm your account, then return here to log in.":"Kontrollo email-in për të konfirmuar llogarinë, pastaj kthehu këtu për të hyrë.",
  "The login session could not be created.":"Sesioni i hyrjes nuk mund të krijohej.",
  "Account access failed. Try again.":"Hyrja në llogari dështoi. Provo përsëri.",
  "Google sign-in could not start.":"Hyrja me Google nuk mund të nisej.",
  "Enter your email first.":"Shkruaj fillimisht email-in.",
  "Forgot password?":"Ke harruar fjalëkalimin?",
  "Password reset link sent. Check your email.":"Lidhja për rivendosjen e fjalëkalimit u dërgua. Kontrollo email-in.",
  "The reset email could not be sent.":"Email-i i rivendosjes nuk mund të dërgohej.",
  "Continue with Google":"Vazhdo me Google",
  "or":"ose",
  "Authentication is handled securely by Supabase. Hiddentify never stores your password.":"Hyrja menaxhohet në mënyrë të sigurt nga Supabase. Hiddentify nuk e ruan kurrë fjalëkalimin tënd.",
  "Sign in before choosing your username.":"Hyr në llogari para se të zgjedhësh username-in.",
  "The profile could not be saved.":"Profili nuk mund të ruhej.",
  "ACCOUNT RECOVERY":"RIKUPERIMI I LLOGARISË",
  "Choose a new password":"Zgjidh një fjalëkalim të ri",
  "Checking recovery link…":"Duke kontrolluar lidhjen e rikuperimit…",
  "New password":"Fjalëkalimi i ri",
  "Your password could not be changed.":"Fjalëkalimi nuk mund të ndryshohej.",
  "Changing password…":"Duke ndryshuar fjalëkalimin…",
  "Change password":"Ndrysho fjalëkalimin",
  "Your password has been changed.":"Fjalëkalimi u ndryshua.",
  "Return to Hiddentify":"Kthehu te Hiddentify",
  "This recovery link is missing or has expired. Request a new link from the login screen.":"Kjo lidhje rikuperimi mungon ose ka skaduar. Kërko një lidhje të re nga faqja e hyrjes.",
  "Return to login":"Kthehu te hyrja",
  "Back to entry options":"Kthehu te mënyrat e hyrjes",
  "Playing as":"Po luan si",
  "Registered account":"Llogari e regjistruar",
  "Temporary guest":"Vizitor i përkohshëm",
  "Change":"Ndrysho",
  "Log out":"Dil nga llogaria",
  "Your account keeps your username and lets you reconnect to rooms from another device.":"Llogaria ruan username-in dhe të lejon të rilidhesh me dhomat nga një pajisje tjetër.",
  "Guest names are only used for the current room.":"Emrat e vizitorëve përdoren vetëm për dhomën aktuale.",
  "Open a private room":"Hap një dhomë private",
  "Use your invitation code":"Përdor kodin e ftesës",
  "Create case":"Krijo çështje",
  "Join case":"Hyr në çështje",
  "Your name":"Emri yt",
  "Room code":"Kodi i dhomës",
  "Create private room":"Krijo dhomë private",
  "Join the investigation":"Hyr në hetim",
  "Friends join from their own phones using the five-character code.":"Miqtë hyjnë nga telefonat e tyre me kodin pesëshkronjësh.",
  "The lineup":"Të dyshuarit",
  "Everyone looks suspicious for a reason.":"Të gjithë duken të dyshimtë për një arsye.",
  "Innocent players also hide mistakes, debts, secret meetings, and private objectives. Catching somebody in a lie does not automatically make them the killer.":"Edhe lojtarët e pafajshëm fshehin gabime, borxhe, takime sekrete dhe objektiva private. Të kapësh dikë në gënjeshtër nuk do të thotë automatikisht se është vrasësi.",
  "The board is waiting":"Tabela po pret",
  "Somebody has to solve it.":"Dikush duhet ta zgjidhë.",
  "Open a room, send the link to your friends, and discover who can control the story without getting caught.":"Hap një dhomë, dërgoju miqve lidhjen dhe zbulo kush mund ta kontrollojë historinë pa u kapur.",
  "No case is ever quite the same.":"Asnjë çështje nuk është kurrë njësoj.",
  "Waiting room":"Dhoma e pritjes",
  "Assemble the suspects":"Mblidh të dyshuarit",
  "Link copied":"Lidhja u kopjua",
  "Invite friends":"Fto miqtë",
  "Friends open the link, enter their name, and join from their own phone.":"Miqtë hapin lidhjen, shkruajnë emrin dhe hyjnë nga telefoni i tyre.",
  "Players":"Lojtarët",
  "Choose the experience":"Zgjidh përvojën",
  "Casual or Detective":"Casual ose Detektiv",
  "Selected mode":"Modaliteti i zgjedhur",
  "Casual":"E thjeshtë",
  "Detective":"Detektiv",
  "CASUAL":"E THJESHTË",
  "DETECTIVE":"DETEKTIV",
  "Fast and simple":"E shpejtë dhe e thjeshtë",
  "Full investigation":"Hetimi i plotë",
  "Exactly three key evidence envelopes, a shorter character folder, and face-to-face discussion. No powers, action menus, or private interrogations.":"Saktësisht tri zarfe me prova kryesore, një dosje personazhi më e shkurtër dhe diskutim ballë për ballë. Pa fuqi, menu veprimesh apo marrje në pyetje private.",
  "Four evidence packets, private investigation moves, unique powers, covert killer actions, and private interrogations.":"Katër pako provash, veprime hetimore private, fuqi unike, ndërhyrje të fshehta të vrasësve dhe marrje në pyetje private.",
  "What happens":"Çfarë ndodh",
  "Innocent role":"Roli i të pafajshmit",
  "Killer role":"Roli i vrasësit",
  "Quick role folder":"Dosje e shkurtër e rolit",
  "Say aloud":"Thuaje me zë",
  "Keep private":"Mbaje private",
  "Your mission":"Misioni yt",
  "Choose the hidden team":"Zgjidh ekipin e fshehtë",
  "How many killers?":"Sa vrasës?",
  "More options unlock as friends join. Innocent players always remain the larger side.":"Më shumë mundësi hapen kur hyjnë miqtë. Lojtarët e pafajshëm mbeten gjithmonë shumica.",
  "Generate case & assign roles":"Krijo çështjen dhe cakto rolet",
  "Only you, the host, can choose the mode, team size, start, and release evidence.":"Vetëm ti, si drejtues, mund të zgjedhësh mënyrën, numrin e vrasësve, nisjen dhe publikimin e provave.",
  "Waiting for the host to start…":"Duke pritur drejtuesin të nisë…",
  "Case briefing · Read before play":"Udhëzimi i çështjes · Lexoje para lojës",
  "How to play Hiddentify":"Si luhet Hiddentify",
  "The app protects the secrets. Your group investigates by talking, questioning, bluffing, and deciding which story explains every clue.":"Aplikacioni ruan sekretet. Grupi heton duke biseduar, pyetur, mashtruar dhe vendosur cila histori shpjegon çdo provë.",
  "3–10 players":"3–10 lojtarë",
  "1–4 killers":"1–4 vrasës",
  "One phone each":"Një telefon secili",
  "2 ways to play":"2 mënyra loje",
  "Safe to say aloud":"Mund t'i thuash me zë",
  "Your character’s name, job, public background, and any clue you choose to share.":"Emrin, punën dhe historinë publike të personazhit, si edhe çdo provë që zgjedh të ndash.",
  "Keep on your phone":"Mbaji në telefon",
  "Your secret, objective, true movements, power result, and private messages—unless revealing one helps your strategy.":"Sekretin, objektivin, lëvizjet e vërteta, rezultatin e fuqisë dhe mesazhet private—përveçse kur zbulimi të ndihmon në strategji.",
  "The rule that decides the winner":"Rregulli që vendos fituesin",
  "Each ballot must identify the full hidden team. More than half of all ballots must match every killer exactly. The killers’ ballots count too; a tied, split, or partly correct result means the killer team wins.":"Çdo votë duhet të identifikojë gjithë ekipin e fshehtë. Më shumë se gjysma e votave duhet të përputhen saktësisht me çdo vrasës. Edhe votat e vrasësve numërohen; barazimi, ndarja ose përgjigjja pjesërisht e saktë u jep fitoren vrasësve.",
  "Got it—open the case":"E kuptova—hap çështjen",
  "Live case":"Çështje aktive",
  "Active investigation":"Hetim aktiv",
  "Accusations open":"Akuzat janë hapur",
  "Role":"Roli",
  "Clues":"Provat",
  "Actions":"Veprimet",
  "Released evidence arrives sealed. Tap each envelope to unfold the clue on your own phone.":"Provat vijnë të vulosura. Prek çdo zarf për ta hapur provën në telefonin tënd.",
  "The first evidence envelope is sealed.":"Zarfi i parë i provave është i vulosur.",
  "Give everyone time to read their private role before opening the case.":"Jepu të gjithëve kohë të lexojnë rolin privat para se të hapësh çështjen.",
  "Open first evidence packet":"Hap pakon e parë të provave",
  "Release next evidence packet":"Publiko pakon tjetër të provave",
  "Waiting for the host to open the first evidence packet…":"Duke pritur drejtuesin të hapë pakon e parë të provave…",
  "Evidence":"Prova",
  "Packet":"Pakoja",
  "Sealed":"E vulosur",
  "Breaking the seal…":"Duke thyer vulën…",
  "Tap to open":"Prek për ta hapur",
  "Private role assignment":"Caktim privat i rolit",
  "Make sure nobody is looking over your shoulder.":"Sigurohu që askush nuk po sheh ekranin tënd.",
  "Every player receives a different sealed folder. Open yours only when you are ready to meet your character.":"Çdo lojtar merr një dosje të ndryshme të vulosur. Hape vetëm kur të jesh gati të njohësh personazhin.",
  "PRIVATE ROLE FOLDER":"DOSJE PRIVATE E ROLIT",
  "CLASSIFIED CASE FOLDER":"DOSJE E KLASIFIKUAR",
  "FICTIONAL GAME CASE":"ÇËSHTJE LOJE IMAGJINARE",
  "PERSONNEL ASSIGNMENT · CLASSIFIED":"CAKTIM PERSONAZHI · I KLASIFIKUAR",
  "EYES ONLY":"VETËM PËR TY",
  "One private identity is filed inside":"Brenda ndodhet një identitet privat",
  "Opening folder…":"Duke hapur dosjen…",
  "Open folder":"Hap dosjen",
  "Folder opened · private clearance granted":"Dosja u hap · hyrja private u lejua",
  "You can reopen your folder from the Role tab.":"Mund ta rihapësh dosjen te skeda Roli.",
  "Final majority vote":"Vota përfundimtare e shumicës",
  "Select the full team":"Zgjidh gjithë ekipin",
  "Lock my complete ballot":"Mbyll votën time",
  "Reveal vote & winner":"Zbulo votat dhe fituesin",
  "Final vote revealed":"Vota përfundimtare u zbulua",
  "Majority matched the full team":"Shumica gjeti gjithë ekipin",
  "No majority for the full team":"Nuk pati shumicë për ekipin e plotë",
  "Motive":"Motivi",
  "Method":"Metoda",
  "Major revelation":"Zbulimi kryesor",
  "What actually happened":"Çfarë ndodhi në të vërtetë",
  "True-crime murder echo · unlocked":"Jehona e një vrasjeje reale · u hap",
  "Inspired by":"Frymëzuar nga",
  "Secret vote breakdown":"Ndarja e votave sekrete",
  "Exact team":"Ekipi i saktë",
  "Wrong or partial team":"Ekip i gabuar ose i paplotë",
  "Create or join another room":"Krijo ose hyr në një dhomë tjetër",
  "Public background":"Historia publike",
  "Your secret":"Sekreti yt",
  "Claimed alibi":"Alibia e pretenduar",
  "What really happened":"Çfarë ndodhi vërtet",
  "What you know":"Çfarë di ti",
  "Private objective":"Objektivi privat",
  "Location":"Vendndodhja",
  "Victim":"Viktima",
  "Incident":"Incidenti",
  "Role not assigned":"Roli nuk është caktuar",
  "Acted":"Veproi",
  "Thinking":"Po mendon",
  "acted":"kanë vepruar",
  "Open private room":"Hap dhomë private",
  "Accept":"Prano",
  "Decline":"Refuzo",
  "Character":"Personazhi",
  "You":"Ti",
  "you":"ti",
  "Round":"Raundi",
  "Target":"Objektivi",
  "Private move":"Veprim privat",
  "Awaiting first evidence":"Në pritje të provës së parë",
  "Investigation closed":"Hetimi u mbyll",
  "Read your role and introduce only your public identity. Actions unlock when the host opens the first packet.":"Lexo rolin dhe prezanto vetëm identitetin publik. Veprimet hapen kur drejtuesi publikon pakon e parë.",
  "All private actions are complete. Compare your discoveries, challenge the unverified signals, and prepare your final vote.":"Të gjitha veprimet private përfunduan. Krahasoni zbulimet, sfidoni sinjalet e paverifikuara dhe përgatitni votën përfundimtare.",
  "COVERT MOVE LOCKED":"VEPRIMI I FSHEHTË U MBYLL",
  "INVESTIGATION COMPLETE":"HETIMI PËRFUNDOI",
  "This result is private. Reveal it, hide it, or describe it strategically when talking to the group.":"Ky rezultat është privat. Zbuloje, fshihe ose përshkruaje me strategji kur bisedon me grupin.",
  "Only you can see the covert moves.":"Vetëm ti i sheh veprimet e fshehta.",
  "You may investigate normally or sacrifice this round’s investigation to mislead the room. Essential evidence cannot be destroyed.":"Mund të hetosh normalisht ose ta sakrifikosh veprimin e këtij raundi për të çorientuar grupin. Provat thelbësore nuk mund të shkatërrohen.",
  "Choose one action":"Zgjidh një veprim",
  "Select your move":"Zgjidh veprimin",
  "Covert":"I fshehtë",
  "Choose a target":"Zgjidh një objektiv",
  "Select a player":"Zgjidh një lojtar",
  "Select another player":"Zgjidh një lojtar tjetër",
  "Execute covert move":"Kryej veprimin e fshehtë",
  "Lock private action":"Mbyll veprimin privat",
  "Your choice cannot be changed after it is locked.":"Zgjedhja nuk mund të ndryshohet pasi të mbyllet.",
  "Earlier discoveries":"Zbulimet e mëparshme",
  "Open channel":"Kanali i hapur",
  "Unverified signals":"Sinjale të paverifikuara",
  "These reports may be useful, forged, or planted by the killer. They are never required to solve the case.":"Këto raporte mund të jenë të dobishme, të falsifikuara ose të vendosura nga vrasësi. Ato nuk janë kurrë të nevojshme për ta zgjidhur çështjen.",
  "No suspicious transmission has appeared yet.":"Ende nuk është shfaqur asnjë transmetim i dyshimtë.",
  "Search the scene":"Kontrollo skenën",
  "Inspect physical traces and receive one private observation.":"Kontrollo gjurmët fizike dhe merr një vëzhgim privat.",
  "Analyze the evidence":"Analizo provat",
  "Test how the released clues fit together and uncover a hidden detail.":"Provo si lidhen provat e publikuara dhe zbulo një detaj të fshehur.",
  "Check digital records":"Kontrollo regjistrat digjitalë",
  "Examine schedules, access logs, and timestamps for contradictions.":"Kontrollo oraret, hyrjet dhe kohët për kundërshtime.",
  "Probe an alibi":"Kontrollo një alibi",
  "Analyze one character's account and privately assess the weakness in their story.":"Analizo tregimin e një personazhi dhe vlerëso privatisht dobësinë e tij.",
  "Plant a false trail":"Vendos një gjurmë të rreme",
  "Publish an unauthenticated trace that points toward another suspect.":"Publiko një gjurmë të pavërtetuar që drejton te një i dyshuar tjetër.",
  "Send an anonymous tip":"Dërgo një mesazh anonim",
  "Publicly direct the room's suspicion toward another suspect.":"Drejto publikisht dyshimin e grupit te një i dyshuar tjetër.",
  "Forge an alibi":"Falsifiko një alibi",
  "Publish a late-synced record that appears to clear you or any other character.":"Publiko një regjistër të vonuar që duket se të shfajëson ty ose një personazh tjetër.",
  "Delay an investigation":"Vono një hetim",
  "Hide one player's private result until the next evidence packet.":"Fshih rezultatin privat të një lojtari deri te pakoja tjetër e provave.",
  "Unique role power":"Fuqia unike e rolit",
  "Unique role power · once per case":"Fuqia unike · një herë në lojë",
  "Unique power":"Fuqi unike",
  "Available in newly generated cases":"E disponueshme në çështjet e reja",
  "This case began before character abilities were added. Your normal investigation actions still work.":"Kjo çështje nisi para se të shtoheshin fuqitë. Veprimet normale të hetimit ende funksionojnë.",
  "Power used":"Fuqia u përdor",
  "Only you can see this result.":"Vetëm ti mund ta shohësh këtë rezultat.",
  "Choose one suspect":"Zgjidh një të dyshuar",
  "Role powers open during evidence rounds 1–3.":"Fuqitë hapen gjatë raundeve 1–3 të provave.",
  "Private interrogation · one invite per case":"Marrje në pyetje private · një ftesë në lojë",
  "Two minutes. Two players.":"Dy minuta. Dy lojtarë.",
  "Invite one suspect. If they accept within 45 seconds, a private two-person text channel opens for two minutes. The rest of the room cannot read it.":"Fto një të dyshuar. Nëse pranon brenda 45 sekondave, hapet një bisedë private dyminutëshe. Pjesa tjetër e grupit nuk mund ta lexojë.",
  "wants to question you privately.":"dëshiron të të marrë në pyetje privatisht.",
  "The invitation closes automatically.":"Ftesa mbyllet automatikisht.",
  "max 40 messages":"maksimumi 40 mesazhe",
  "Channel open. Ask a direct question.":"Kanali u hap. Bëj një pyetje të drejtpërdrejtë.",
  "Write a private message…":"Shkruaj një mesazh privat…",
  "Send private message":"Dërgo mesazhin privat",
  "Choose who to invite":"Zgjidh kë do të ftosh",
  "Send private invitation":"Dërgo ftesë private",
  "Invitations open during evidence rounds 1–3.":"Ftesat hapen gjatë raundeve 1–3 të provave.",
  "Your invitation has been used. You can still accept an invitation from another player.":"Ftesa jote është përdorur. Ende mund të pranosh një ftesë nga një lojtar tjetër.",
  "Covert advantage":"Përparësi e fshehtë",
  "During each of the first three evidence rounds, open the Actions tab. You may investigate normally or secretly create interference. Other phones never reveal which killer caused it.":"Në secilin nga tri raundet e para, hap skedën Veprimet. Mund të hetosh normalisht ose të krijosh fshehurazi një ndërhyrje. Telefonat e tjerë nuk zbulojnë cili vrasës e shkaktoi.",
  "Use it from Actions during rounds 1–3.":"Përdore te Veprimet gjatë raundeve 1–3.",
  "Do not show this screen to anyone. You may lie about your secrets, but do not contradict facts the app has released.":"Mos ia trego këtë ekran askujt. Mund të gënjesh për sekretet, por mos kundërshto faktet që aplikacioni ka publikuar.",
  "Role power used":"Fuqia e rolit u përdor",
  "Connection lost":"Lidhja u ndërpre",
  "This room is unavailable.":"Kjo dhomë nuk është e disponueshme.",
  "Try again":"Provo përsëri",
  "You are offline. Reconnect to Wi-Fi or mobile data and the room will resume automatically.":"Je pa internet. Rilidhu me Wi-Fi ose internetin celular dhe dhoma do të vazhdojë automatikisht.",
  "Connection interrupted. Reconnecting automatically…":"Lidhja u ndërpre. Po rilidhemi automatikisht…",
  "Connection interrupted. Check your internet and try again.":"Lidhja u ndërpre. Kontrollo internetin dhe provo përsëri.",
};

type LanguageContextValue={language:Language;setLanguage:(language:Language)=>void;t:(english:string)=>string};
const LanguageContext=createContext<LanguageContextValue>({language:"en",setLanguage:()=>{},t:value=>value});

export function LanguageProvider({children}:{children:ReactNode}){
  const[language,setLanguageState]=useState<Language>("en");
  useEffect(()=>{const saved=localStorage.getItem(LANGUAGE_STORE),timer=saved==="sq"?window.setTimeout(()=>setLanguageState("sq"),0):null;return()=>{if(timer!==null)window.clearTimeout(timer)}},[]);
  useEffect(()=>{document.documentElement.lang=language;localStorage.setItem(LANGUAGE_STORE,language)},[language]);
  const setLanguage=useCallback((next:Language)=>setLanguageState(next),[]),t=useCallback((english:string)=>language==="sq"?(sq[english]??english):english,[language]);
  const value=useMemo(()=>({language,setLanguage,t}),[language,setLanguage,t]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage(){return useContext(LanguageContext)}
export function choose(language:Language,english:string,albanian:string){return language==="sq"?albanian:english}

export function LanguageToggle({compact=false}:{compact?:boolean}){
  const{language,setLanguage,t}=useLanguage();
  return <div className="flex items-center rounded-lg border border-white/15 bg-black/25 p-0.5" role="group" aria-label={t("Language")} title={t("Language")}>
    <button type="button" onClick={()=>setLanguage("en")} aria-pressed={language==="en"} className={`rounded-md px-2 py-1 text-[11px] font-semibold tracking-wider transition ${language==="en"?"bg-amber-100 text-stone-950":"text-slate-400 hover:text-white"}`}>{compact?"EN":"EN"}</button>
    <button type="button" onClick={()=>setLanguage("sq")} aria-pressed={language==="sq"} className={`rounded-md px-2 py-1 text-[11px] font-semibold tracking-wider transition ${language==="sq"?"bg-amber-100 text-stone-950":"text-slate-400 hover:text-white"}`}>SH</button>
  </div>;
}
